### ISSUE TITLE
Elysium artwork

### ISSUE THREAD

**Issue by bjgood** [OpenELEQ/repository.elysium#1]
Hi,
You can fix where Elysium artwork is not showing in Elysium 06.10.2017 by changing script.elysium.artwork/resources/media/Elysium to script.elysium.artwork/resources/media/elysium. After making that simple change the artwork will show in the Elysium plugin.

Hope it helps.

Bob

**Comment by OpenELEQ** [comment]
Thanks for the report. It iss fixed so closing this issue.
